# Generated by Django 4.0.2 on 2022-02-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(default=10, max_length=200, verbose_name='Digite seu telefone'),
            preserve_default=False,
        ),
    ]
