# Generated by Django 4.0.2 on 2022-03-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_projetos_tarefas_check_list_tarefas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
