# Generated by Django 4.0.2 on 2022-03-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_delete_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='id_user_group',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='se_ativo',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='updated',
        ),
    ]
