# Generated by Django 4.0.2 on 2022-03-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_remove_projetos_created_remove_projetos_id_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projetos',
            new_name='ProjetosModel',
        ),
    ]
